service: trmnl-dsn

image: schrockwell/trmnl-dsn

retain_containers: 1

servers:
  web:
    - trmnl-dsn.schrockwell.com

proxy:
  ssl: true
  host: trmnl-dsn.schrockwell.com
  app_port: 3000

registry:
  server: localhost:5555

builder:
  arch: amd64
